version: '3.8'

services:
  web:
    image: custom-nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - nginx_certs:/etc/nginx/ssl
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - inception-network
    healthcheck:
      test: [ "CMD", "curl", "-k", "http://localhost:443" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  wordpress:
    image: custom-wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    volumes:
      - wordpress:/var/www/html
    secrets:
      - DB_PASSWORD
      - WP_ADMIN_PASSWORD
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_ADMIN_PASSWORD_FILE: run/secrets/wp_admin_password
      DB_PASSWORD_FILE: run/secrets/db_password
    restart: unless-stopped
    networks:
      - inception-network
    healthcheck:
      test: [ "CMD", "nc", "-z", "wordpress", "9000" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      - mariadb
  mariadb:
    image: custom-mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    secrets:
      - DB_ROOT_PASSWORD
      - DB_PASSWORD
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD_FILE: run/secrets/db_password
      DB_ROOT_PASSWORD_FILE: run/secrets/db_root_password
    networks:
      - inception-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "sh", "-c", "mysqladmin ping -h localhost -u root -p$$(cat /run/secrets/db_root_password)" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  inception-network:
    driver: bridge

volumes:
  nginx_certs:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/muxammad/Desktop/Inception/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/muxammad/Desktop/Inception/data/mariadb

secrets:
  DB_ROOT_PASSWORD:
    file: ../secrets/db_root_password.txt
  DB_PASSWORD:
    file: ../secrets/db_password.txt
  WP_ADMIN_PASSWORD:
    file: ../secrets/credentials.txt
